#!/usr/bin/awk -f

# 行頭コメントは読み飛ばす
/^#/ {
    next
}

{
    trainnum_idx = match($0, /:/)
    if (trainnum_idx != 0) {
        trainnum = substr($0, 1, trainnum_idx-1)
        formation = substr($0, trainnum_idx+1)
        gsub(/ /, "", formation)
    }
    print trainnum, formation
}
