#!/bin/bash -eux

# 設定読み込み
source "$(dirname $0)/bin/conf"

[ "$USER"="root" ] #USER MUST BE ROOT

# PULL DATA
rm -rf "${contentsdir:?}"
cd "$wwwdir"
git clone "https://github.com/$contents_owner/$contents"
chown raindrop.jp-aotake-rail:LolipopUser "$contentsdir" -R
