#!/bin/bash -eux

# 設定読み込み
source "$(dirname $0)/bin/conf"

[ "$USER"="root" ] #USER MUST BE ROOT

# INSTALL THIS SYSTEM
rsync -av --delete "$(dirname $0)/bin/" "$appdir/"

### EDIT FETCH CGI ###
cd "$appdir"
rnd=$(cat /dev/urandom | tr -cd 0-9a-zA-Z | head -c 32)
mv "fetch" "fetch_$rnd.cgi"

# PULL DATA
rm -rf "${contentsdir:?}"
cd "$wwwdir"
git clone "https://github.com/$contents_owner/$contents"

echo "call fetch_$rnd.cgi from GitHub"
